# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

e_monteCPP <- function(x, rin, K, Kmin, par1, par2, type) {
    .Call(`_echelon_e_monteCPP`, x, rin, K, Kmin, par1, par2, type)
}

